###################################################### DATABASE CONFIGURATION ###########################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb2?createDatabaseIfNotExist=true
    username: root
    password: passer20dk2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: create


####################################################### MY PROPERTIES ##################################################

sn:
  gainde2000:
    starter-auth-service:
      nameEnterprise: ATOS
      logoEnterprise: 
      emailEnterprise: atos@atos.sn
      descriptionEnterprise: Entreprise informatique ...


springdoc:
  api-docs:
    path: /documentation


###################################################### EUREKA CONFIG ###################################################

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
