# API GATEWAY CONFIG FILE

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true  
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        #===========================================
        # POST SERVICE
        - id: posts-service
          uri: lb://posts-service
          predicates:
            - Path=/api/posts, /api/posts/{id}
            - Method=GET,POST,OPTIONS,PUT,DELETE
        #============================================
        # DISCOVERY SERVICE
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        #=============================================
        # DISCOVERY SERVICE STATIC FILES
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8088


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    hostname: localhost


