spring:
  datasource:
    url: jdbc:mysql://localhost:3306/announcedb
    username: root
    password: passer20dk2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    hostname: localhost
